# Generated by Django 5.2.7 on 2025-10-04 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Climb',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('route', models.CharField()),
                ('area', models.CharField()),
                ('climbed', models.BooleanField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Climber',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('climbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climb_app.climb')),
            ],
        ),
    ]
