# Generated by Django 5.2.7 on 2025-10-05 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climb',
            name='area',
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climb_app.area')),
            ],
        ),
        migrations.AlterField(
            model_name='climb',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climb_app.route'),
        ),
    ]
