# Generated by Django 5.2.7 on 2025-10-05 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_app', '0002_remove_climb_area_route_alter_climb_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(default='default'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='climber',
            name='climbs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climb_app.climb'),
        ),
    ]
