# Generated by Django 5.2.7 on 2025-10-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_app', '0003_route_name_alter_climber_climbs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climber',
            name='climbs',
        ),
        migrations.AddField(
            model_name='climb',
            name='climbers',
            field=models.ManyToManyField(related_name='climbs', to='climb_app.climber'),
        ),
    ]
