# Generated by Django 5.2.7 on 2025-10-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climb_app', '0005_alter_area_id_alter_climb_id_alter_climber_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climb',
            name='climbed',
        ),
    ]
