# Generated by Django 5.2.7 on 2025-10-05 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_app', '0006_remove_climb_climbed'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='country',
            field=models.CharField(default='Austria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='climb',
            name='comment',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route',
            name='grade',
            field=models.CharField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='more_info_at',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='prio',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='type',
            field=models.CharField(choices=[('sport', 'Sport'), ('semi-alpine', 'Semi-alpine'), ('alpine', 'Alpine'), ('trad', 'Trad')], default='sport'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NearestReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climb_app.area')),
            ],
        ),
    ]
