# Generated by Django 5.2.7 on 2025-10-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_app', '0007_area_country_climb_comment_route_done_route_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='prio',
            field=models.IntegerField(choices=[(3, 'Low'), (2, 'Medium'), (1, 'High')]),
        ),
    ]
