# Generated by Django 5.2.7 on 2025-10-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_app', '0008_alter_route_prio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb',
            name='comment',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='done',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='grade',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='more_info_at',
            field=models.CharField(blank=True, null=True),
        ),
    ]
