# Generated by Django 5.2.7 on 2025-10-05 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_app', '0009_alter_climb_comment_alter_route_done_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='area',
        ),
        migrations.AddField(
            model_name='route',
            name='nearest_reference',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='climb_app.nearestreference'),
            preserve_default=False,
        ),
    ]
