# Generated by Django 5.2.7 on 2025-10-05 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_app', '0011_alter_route_nearest_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='nearest_reference',
            field=models.ForeignKey(blank=True, default='Rifugio Treviso', null=True, on_delete=django.db.models.deletion.CASCADE, to='climb_app.nearestreference'),
        ),
    ]
