# Generated by Django 5.2.7 on 2025-10-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_app', '0013_alter_route_nearest_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='prio',
            field=models.IntegerField(blank=True, choices=[(3, 'Low'), (2, 'Medium'), (1, 'High')], null=True),
        ),
    ]
