# Generated by Django 5.2.7 on 2025-10-07 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_app', '0014_alter_route_prio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='country',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nearestreference',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climb_app.area'),
        ),
    ]
