# Generated by Django 5.2.7 on 2025-10-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_app', '0015_alter_area_country_alter_area_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearestreference',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
