# Generated by Django 5.2.7 on 2025-10-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_app', '0016_alter_nearestreference_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climb',
            name='comment',
        ),
        migrations.AddField(
            model_name='route',
            name='comment',
            field=models.CharField(blank=True, null=True),
        ),
    ]
